In [1]:
import numpy as np

### create array

In [4]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [9]:
zeroes = np.zeros((3,2))
#x merupakan baris, y adalah kolom
print(zeroes)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
ones = np.ones((2,2))
print(ones)

[[1. 1.]
 [1. 1.]]


In [13]:
range_arr = np.arange(1, 8, 3)
print(range_arr)

[1 4 7]


In [18]:
linspace_arr = np.linspace(1, 3, 4)
print(linspace_arr)

[1.         1.66666667 2.33333333 3.        ]


### manipulating arrays

In [22]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape((3,2))
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
expanded = arr[:, np.newaxis]
print(expanded)


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### basic

In [29]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [30]:
arr = np.array([4, 16, 25])

In [33]:
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))

[2. 4. 5.]
45
15.0
25


### indexing, slicing, and reshaping

In [41]:
arr = np.array([10, 20, 30 , 40, 50, 60])
print(arr[2])
print(arr[-1])


print(arr[1:4])
print(arr[:3])

reshaped = arr.reshape(2,3)
print(reshaped)

30
60
[20 30 40]
[10 20 30]
[[10 20 30]
 [40 50 60]]


## Exercise 1 = generate arrayys for basic mathematical operactions

In [47]:
a = np.arange(1,5)
b = np.arange(7,11)

print(a)
print(b)

print("Add: ", a + b)
print("Subsctract: ", a - b)
print("Multiplication: ", a * b)
print("Div: ", a / b)

Add:  [ 8 10 12 14]
Subsctract:  [-6 -6 -6 -6]
Multiplication:  [ 7 16 27 40]
Div:  [0.14285714 0.25       0.33333333 0.4       ]


## create 3x3 matrix and perform operations

In [52]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(f"original matrix: \n{matrix}")

original matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [54]:
#transpose
transpose = matrix.T
print(f"transpose matrix: \n: {transpose}")

transpose matrix: 
: [[1 4 7]
 [2 5 8]
 [3 6 9]]
