In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(arr + 10)

[11 12 13]


In [3]:
matrix = np.array([[1,2,3], [4,5,6]])
vector = np.array([1,0,1])
print(matrix + vector)

[[2 2 4]
 [5 5 7]]


### aggregation funct

In [6]:
arr = np.array([[1,2,3], [4,5,6]])
print(f"sum: {np.sum(arr)}")
print(f"std dev: {np.std(arr)}")
print(f"sum along rows: {np.sum(arr, axis=1)}")
print(f"sum along cols: {np.sum(arr, axis=0)}")


sum: 21
std dev: 1.707825127659933
sum along rows: [ 6 15]
sum along cols: [5 7 9]


In [7]:
#Boolean indexing and filtering

arr = np.array([1,2,3,4,5,6])

evens = arr[arr % 2 == 0]
print("evens: ", evens)

arr[arr > 3] = 1
print("modified arr: ", arr)

evens:  [2 4 6]
modified arr:  [1 2 3 1 1 1]


In [8]:
#Random number generation and Setting Seeds
np.random.seed(42)

#supaya selalu sama dalam setiap devices

## Exercise 1

In [10]:
matrix = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
vector = np.array([1, 0, -1])

result_add = matrix +vector
print("Add: \n", result_add)

mul = matrix * 2
print("multipication : \n", mul)

Add: 
 [[2 2 2]
 [5 5 5]
 [8 8 8]]
multipication : 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Exercise 2
generate and filter a random dataset

In [12]:
dataset = np.random.randint(1, 51, size=(5,5))
print("original dataset: \n", dataset)

original dataset: 
 [[12 22 44 25 49]
 [27 42 28 16 15]
 [47 44  3 37  7]
 [21  9 39 18  4]
 [25 14 50  9 26]]


In [13]:
dataset[dataset > 25] = 0
print("modified: \n", dataset)

modified: 
 [[12 22  0 25  0]
 [ 0  0  0 16 15]
 [ 0  0  3  0  7]
 [21  9  0 18  4]
 [25 14  0  9  0]]


In [15]:
print(f"sum: {np.sum(dataset)}")
print(f"mean: {np.mean(dataset)}")

sum: 200
mean: 8.0
